# Generated by Django 3.2.5 on 2021-07-31 12:43

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


def country_table(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Cities = apps.get_model("dealers", "City")
    Country = apps.get_model("dealers", "Country")
    for city in Cities.objects.all():
        city.country = models.ForeignKey('dealers.City', on_delete=models.CASCADE, )
        if Country.objects.filter(name='Украина').count():
            city.country = Country.objects.get(name='Украина').id
        else:
            new_country = Country.objects.create(name=city.country)
            city.country = new_country.id

        city.save()



class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('dealers', '0002_auto_20210731_1123'),
    ]

    operations = [
        migrations.RunPython(country_table)
    ]
