# Generated by Django 3.2.5 on 2021-07-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_alter_country_code'),
        ('dealers', '0006_auto_20210731_1339'),
    ]

    operations = [
    ]
