# Generated by Django 3.2.5 on 2021-07-31 13:55

from django.db import migrations, models


def country_table(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Cities = apps.get_model("dealers", "City")
    Country = apps.get_model("dealers", "Country")
    for city in Cities.objects.all():
        print(city.country)
        if Country.objects.filter(name=city.country).count():
            city.country = Country.objects.get(name=city.country).id
            # city.save()
            print("Update")
        else:
            Country.objects.create(name=city.country)
            city.country = Country.objects.get(name=city.country).id
            print("Create")

            # city.country = new_country.id
        city.save()
        print(city.country)
    print('Migration done')


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0007_merge_0005_alter_country_code_0006_auto_20210731_1339'),
    ]

    operations = [
        migrations.RunPython(country_table),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='dealers.country'),
        ),
    ]
