# Generated by Django 3.2.5 on 2021-08-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card',
            new_name='car',
        ),
    ]
