# Generated by Django 3.2.6 on 2021-08-30 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('metadata', models.TextField(blank=True, null=True)),
                ('url', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('small', 'Small'), ('mid', 'Midsize'), ('large', 'Large'), ('lux', 'Luxury'), ('sport', 'Sports')], default='mid', max_length=20)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, choices=[('internal combustion', 'Internal combustion engine'), ('hybrid', 'Hybrid engine'), ('electric', 'Electric engine')], default='internal combustion', max_length=50)),
                ('pollutant_choice', models.CharField(choices=[('a+', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], default='a', max_length=100)),
                ('car_status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], default='active', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=50000, max_digits=9)),
                ('doors', models.PositiveSmallIntegerField(default=4)),
                ('capacity', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('gear_case', models.CharField(choices=[('manual', 'Manual gear'), ('semi-automatic', 'Semi-automatic gear'), ('automatic', 'Automatic gear')], default='manual', max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=80)),
                ('sitting_place', models.PositiveSmallIntegerField(default=4)),
                ('first_registration_date', models.DateTimeField(auto_now_add=True)),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline fuel'), ('diesel', 'Diesel fuel'), ('electricity', 'Electricity fuel')], default='gasoline', max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.color')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.dealer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.model')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.picture')),
                ('property', models.ManyToManyField(to='cars.Property')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
