# Generated by Django 3.2.6 on 2021-08-30 22:58

from django.db import migrations, models
import django.db.models.deletion


def copy_fuel_types_from_cars(apps, schema_editor):
    Cars = apps.get_model("cars", "Car")
    FuelTypes = apps.get_model("cars", "FuelType")
    for car in Cars.objects.all():
        FuelTypes.objects.get_or_create(fuel_type=car.fuel_type)


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline fuel'), ('diesel', 'Diesel fuel'), ('electricity', 'Electricity fuel')], default='gasoline', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel type',
                'verbose_name_plural': 'Fuel types',
            },
        ),
        migrations.RunPython(copy_fuel_types_from_cars),
    ]
