# Generated by Django 3.2.5 on 2021-07-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('carburetor', 'Carburetor'), ('injector', 'Injector'), ('electric', 'Electric')], default='carburetor', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(choices=[('electricity', 'Electricity'), ('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas')], default='petrol', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Car Sell'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=30)),
                ('doors', models.SmallIntegerField()),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('number', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=75)),
                ('sitting_place', models.SmallIntegerField()),
                ('first_registration_date', models.DateTimeField(auto_now_add=True)),
                ('engine_power', models.SmallIntegerField()),
                ('other', models.TextField(blank=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машини',
            },
        ),
    ]
