# Generated by Django 3.2.5 on 2021-07-31 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='pictures_car')),
                ('position', models.SmallIntegerField(blank=True)),
                ('metadata', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('passenger', 'Passenger car'), ('bus', 'Bus'), ('Truck', 'Truck')], default='passenger', max_length=40)),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='other',
            new_name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(blank=True, to='cars.Property'),
        ),
        migrations.AddField(
            model_name='car',
            name='pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.picture'),
        ),
    ]
