# Generated by Django 3.2.5 on 2021-08-01 05:54

from django.db import migrations, models
import django.db.models.deletion


def fuel_type_table(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Cars = apps.get_model("cars", "Car")
    FuelType = apps.get_model("cars", "FuelType")
    for car in Cars.objects.all():
        print(car.fuel_type)
        if FuelType.objects.filter(fuel_type=car.fuel_type).count():
            car.fuel_type = FuelType.objects.get(fuel_type=car.fuel_type).id
            # city.save()
            print("Update")
        else:
            FuelType.objects.create(fuel_type=car.fuel_type)
            car.fuel_type = FuelType.objects.get(fuel_type=car.fuel_type).id
            print("Create")

            # city.country = new_country.id
        car.save()
        print(car.fuel_type)
    print('Migration done')



class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('electricity', 'Electricity'), ('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas')], default='petrol', max_length=30)),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Топливо',
            },
        ),
        migrations.RunPython(fuel_type_table),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.fueltype'),
        ),
    ]
