# Generated by Django 3.2.5 on 2021-08-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210801_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='population_type',
            field=models.CharField(choices=[('youth', 'Для молодежи'), ('family', 'Для семьи'), ('sportsman', 'Для спортсменов'), ('travelers', 'Для путешественников'), ('all', 'Для всех')], default='all', max_length=30),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas')], default='petrol', max_length=30, unique=True),
        ),
    ]
