# Generated by Django 3.2.5 on 2021-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210803_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gear_case',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('automatic', 'Automatic'), ('robotic', 'Robotic'), ('variable', 'Variable')], default='mechanical', max_length=30),
        ),
    ]
